[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"

[[edge_functions]]
  path = "/proxy-stream"
  function = "proxy-stream"

[[edge_functions]]
  path = "/radio/*"
  function = "proxy-radio"
